### ISSUE TITLE
ImportError: cannot import name 'Tap' from 'tap' 

### ISSUE THREAD

**Issue by ayushnoori** [swansonk14/typed-argument-parser#124]
Hi Kyle, wanted to let you know that, even after installing Tap using `pip install typed-argument-parser`, I am still encountering the following error:
> ImportError: cannot import name 'Tap' from 'tap' 

I'm using an M2 Mac inside a `virtualenv` virtual environment. A similar or same issue was already reported elsewhere: https://github.com/MehdiAbbanaBennani/continual-learning-ogdplus/issues/9, and an external website was linked there which may provide more information about the problem.

**Comment by martinjm97** [comment]
Hi @ayushnoori,

Thank you for your interest in Tap!

The user in that link ran `pip install tap` rather than `pip install typed-argument-parser`. If you ran `pip install typed-argument-parser` then the issue that you face is different.

The only way I could reproduce your error (`ImportError`) was by having a file called `tap.py` in the same directory as the Python script and then running `from tap import Tap`.

If you don't have a `tap.py` file in the same folder and `tap` is not installed, you get `ModuleNotFoundError: No module named 'tap'` instead. 

I recommend removing or renaming any file in the same directory with the name `tap.py` then trying again.

Best, 
Jesse

**Comment by swansonk14** [comment]
Hi @ayushnoori,

Thanks for sharing that issue! I hope Jesse's answer solved your problem, but please let us know if you're still having any issues.

Best,
Kyle

**Comment by ayushnoori** [comment]
Thanks, @martinjm97 and @swansonk14. I couldn't find `tap.py` in the same directory – perhaps I created and deleted this file by mistake. I recreated the virtual environment and this seemed to solve the issue. Looks like this is resolved, will let you know if I run into this issue again.
