### ISSUE TITLE
`underscores_to_dashes` doesn't play nicely with custom types

### ISSUE THREAD

**Issue by ds-stevento** [swansonk14/typed-argument-parser#38]
Hi all,

I recently discovered this library and it seems lovely, thanks for the efforts! While trying out, I bumped into a problem.

Running the following code:
```
from tap import Tap
from pathlib import Path

class ScriptArgumentParser(Tap):
    root_dir: Path
    """The root dir to process."""

    def __init__(self):
        super().__init__(underscores_to_dashes=True)

    def configure(self):
        self.add_argument('--root-dir', '-r', type=Path)

if __name__ == '__main__':
    args = ScriptArgumentParser().parse_args()
```

crashes `tap` with the following message
> ValueError: Variable "root_dir" has type "<class 'pathlib.Path'>" which is not supported by default.

Looking in the code, it seems the type check is done before the replacement of underscores with dashes, causing this problem.

**Update**
Rewriting the `configure` call as such:
```
def configure(self):
        self.add_argument('--root_dir', '-r', type=Path)
```

seems to work well (no duplicate arguments `root-dir` and `root_dir`), but is rather unintuitive to me.

As a side-note, since dashes in argument names is the POSIX-standard way, I'd vote for making this default `True` instead of `False`.

Kind regards,
steven

**Comment by martinjm97** [comment]
Hi Steven, 

We're glad you're enjoying Tap. Thank you for the interesting and reproducible issue!

It looks like as you said, if `underscores_to_dashes=True` then specifying `self.add_argument('--root-dir', '-r', type=Path)
` should refer to the class variable `root_dir`, but that wasn't the case. We've fixed this issue in https://github.com/swansonk14/typed-argument-parser/commit/0dc69b36dfd54c3a5cb07daa92f7f0f680437064 and our next release will include this change. For now, your workaround is the best solution on the current release.

Implicitly in this issue is the concern that we don't support `Path` as a default type (see https://github.com/swansonk14/typed-argument-parser/issues/32). We're working on fixing this in https://github.com/swansonk14/typed-argument-parser/tree/complex-types. 

As to your request regarding dashes in argument names, we feel that the class variable that you write should be the argument that you see on the command line by default. This choice is consistent with the interface provided by `argparse`. We appreciate the suggestion and continue with an open mind. 

Thanks again, and happy tapping!

Best,
Jesse and Kyle

**Comment by ds-stevento** [comment]
Thanks for the followup! I love tapping my Python scripts, this will even make things better!
