### ISSUE TITLE
[suggestion] Use `Annotated` instead of source code parsing.

### ISSUE THREAD

**Issue by LiraNuna** [swansonk14/typed-argument-parser#93]
[`typing.Annotated`](https://docs.python.org/3/library/typing.html#typing.Annotated) was introduced in Python 3.9. It seems like the perfect way to add help strings and other meta information.

```python
class ExampleArguments(Tap):
    workers: Annotated[int, HelpString('The number of workers to run')]
```

Of course that will only work for python 3.9 and above.

**Comment by Cnoor0171** [comment]
I'd like to instead suggest a pattern similar to `dataclass`'s `field` construct instead. Created https://github.com/swansonk14/typed-argument-parser/issues/98 as an alternative

**Comment by swansonk14** [comment]
Hi @LiraNuna,

Thank you for the suggestion! We like your idea, but we are afraid that your solution would not work cleanly for long help strings since the default value would appear after the long help string. We prefer the alternative solution mentioned in https://github.com/swansonk14/typed-argument-parser/issues/98. Thanks again for your suggestion and we would appreciate any thoughts on the alternate solution.

Best,
Jesse and Kyle

**Comment by LiraNuna** [comment]
Thanks for your consideration and for taking a look. Should I close this in favor of #98?
